services:
  # Servidor DNS
  dns:
    container_name: dns
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=America/Fortaleza
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./ISP/DNS/resolved.conf:/etc/systemd/resolved.conf
      - ./ISP/DNS/named.conf:/etc/bind/named.conf
      - ./ISP/DNS/dockerson.zone:/etc/bind/dockerson.zone
    restart: unless-stopped
    networks:
      - rede-ISP
  # Servidor Proxy (Traefik)
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: unless-stopped
    networks:
      - rede-ISP
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ISP/Traefik/traefik-config.yaml:/etc/traefik/traefik.yaml:ro
  
  # Servidor de Email (Postfix/Dovecot)

  # Servidor de Webmail (Roundcube)

networks:
  rede-ISP:
    external: true
  rede-externa:
    external: true
# docker network create <nome_da_network>